# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:50
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
